# Generated by Django 4.2.3 on 2023-07-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='employee Name')),
                ('age', models.CharField(max_length=10, verbose_name='employee Age')),
                ('address', models.TextField(verbose_name='employee address')),
            ],
        ),
    ]
